Repository MBTips/FE-MBTips, pull requests merged in 2025-04, with the labels that each got.

#109 fix: https 조건 수정
  vite.config.ts
Labels: 🐞 Bug

#114 feat: ga4 적용
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/App.tsx
  src/libs/analytics.ts
  src/pages/Content.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 👩‍💻 Feat

#115 5차 배포 Test (Dev -> Main)
  .github/workflows/ci.yml
  package-lock.json
  package.json
  src/App.tsx
  src/libs/analytics.ts
  src/pages/Content.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 👩‍💻 Feat

#108 feat: ToastMessage 공통 컴포넌트 개발 및 Select Info 내 ToastMessage 적용
  src/components/ToastMessage.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#118 fix: hmr 설정 변경
  .github/workflows/ci.yml
  src/libs/analytics.ts
  vite.config.ts
Labels: 🐞 Bug

#119 6차 배포 Test (Dev -> Main)
  .github/workflows/ci.yml
  src/components/ToastMessage.tsx
  src/libs/analytics.ts
  src/pages/SelectInfo.tsx
  vite.config.ts
Labels: 👩‍💻 Feat

#121 fix: add log for ga4
  src/App.tsx
  src/libs/analytics.ts
Labels: 🐞 Bug

#122 7차 배포 Test (Dev -> Main)
  src/App.tsx
  src/libs/analytics.ts
Labels: 👩‍💻 Feat

#124 feat: github actions build 단계에 prod 명시 및 로그 추가
  .github/workflows/ci.yml
  vite.config.ts
Labels: 👩‍💻 Feat

#125 fix: content api 절대경로로 수정
  src/pages/Content.tsx
Labels: 🐞 Bug

#130 fix: ci 수정
  .github/workflows/ci.yml
  src/libs/analytics.ts
Labels: 🐞 Bug

#131 fix: ci 수정
  .github/workflows/ci.yml
Labels: 🐞 Bug

#128 fix: Fast Friend API 필드 수정
  src/pages/SelectInfo.tsx
Labels: 🐞 Bug

#145 feat: 내 정보 화면 리스트 개발
  src/App.tsx
  src/pages/MyInfo.tsx
Labels: 👩‍💻 Feat

#149 feat: chat room UI 개발
  src/components/ChatAction.tsx
  src/components/ChatActionBar.tsx
  src/components/ChatMessage.tsx
  src/components/IntroGuide.tsx
  src/components/input/MessageInput.tsx
  src/pages/Chat.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#153 feat: cicd 설정
  .github/workflows/ci.yml
  vite.config.ts
Labels: 👩‍💻 Feat

#156 fix: GA4 설정 변경
  src/App.tsx
  src/libs/analytics.ts
  src/pages/Content.tsx
Labels: 👩‍💻 Feat

#158 Conflict 해결
  .github/workflows/ci.yml
Labels: 🐞 Bug

#163 feat: chat api 연동 작업
  src/pages/Chat.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#159 Feat/팝업 컴포넌트 공통 컴포넌트화 작업
  src/components/Alert.tsx
  src/components/modal/ActionConfirmModal.tsx
  src/pages/MyInfo.tsx
Labels: 👩‍💻 Feat

#169 fix: MyInfo.tsx에서 Header 잘못 import 되고 있었던 부분 수정
  src/pages/MyInfo.tsx
Labels: 🐞 Bug

#171 feat: 채팅 나가기 팝업 추가
  src/components/header/Header.tsx
  src/components/header/SubHeader.tsx
Labels: 👩‍💻 Feat

#172 fix: MainHeader 비로그인일 때 Profile.svg 뜨는 문제 개선
  src/components/header/MainHeader.tsx
Labels: 🐞 Bug

#175 feat: Content 내 대화 시작하기 버튼 핸들러 구현
  src/constants/CONTENT.ts
  src/pages/Content.tsx
Labels: 👩‍💻 Feat

#176 feat: 이용약관 개인정보처리방침 모달
  src/components/TermsAndPrivacy.tsx
  src/components/modal/TermsAndPrivacyModal.tsx
  src/constants/PRIVACY.ts
  src/constants/TERMS.ts
  src/pages/Login.tsx
Labels: 👩‍💻 Feat

#181 feat: 로그인 상태의 아이콘 이벤트 추가
  src/components/header/MainHeader.tsx
Labels: 👩‍💻 Feat

#182 feat: myinfo 화면 내 terms, privacy modal 연동
  src/components/modal/ActionConfirmModal.tsx
  src/pages/MyInfo.tsx
Labels: 👩‍💻 Feat

#188 feat: ToggleChatTIpsButton 열고 닫히는 기능 구현 완료
  src/components/ChatActionBar.tsx
  src/components/button/ToggleChatTipsButton.tsx
  src/components/tips/TipsMenu.tsx
  src/components/tips/TipsMenuContainer.tsx
  src/index.css
  src/pages/Chat.tsx
  vite.config.ts
Labels: 👩‍💻 Feat

#192 style: 홈페이지 내부 font가 360px일 때 줄바꿈 되는 문제 개선
  src/components/StrokeBanner.tsx
  src/index.css
Labels: 🎨 Style

#194 style: TermsAndPrivacyt 감싸는 div에 pb-4 추가
  src/pages/Login.tsx
Labels: 🎨 Style

#196 style: mbti-test intro 페이지 ui 개선
  src/components/header/SubHeader.tsx
  src/index.css
  src/pages/MbtiTestIntro.tsx
Labels: 🎨 Style

#198 fix: chat icon 이미지 비율 유지
  src/pages/Chat.tsx
Labels: 🐞 Bug

#206 feat: GA click event
  src/components/Banner.tsx
  src/components/button/ChatStartButton.tsx
  src/pages/Chat.tsx
  src/pages/MyInfo.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#207 fix: GA pageview element 제거 작업
  src/App.tsx
  src/libs/analytics.ts
Labels: 👩‍💻 Feat

#211 fix: 채팅 input 하단 고정
  src/pages/Chat.tsx
Labels: 👩‍💻 Feat

#204 feat: mbti test 결과를 select info에 반영
  src/components/button/ChatStartButton.tsx
  src/pages/MbtiTestResult.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#212 Feature/공유하기 모달 구현
  index.html
  public/icon/close.svg
  public/icon/kakaotalk.svg
  public/icon/twitter.svg
  src/components/button/KakaoShareButton.tsx
  src/components/button/ShareButton.tsx
  src/components/button/TwitterShareButton.tsx
  src/components/button/UrlCopyBar.tsx
  src/components/button/UrlCopyButton.tsx
  src/components/header/Header.tsx
  src/components/header/SubHeader.tsx
  src/components/modal/ShareModal.tsx
  src/global.d.ts
  src/index.css
  src/main.tsx
  src/types/virtualFreind.ts
Labels: 👩‍💻 Feat

#215 Feature/홈페이지 로그인 했을 때의 기능 구현
  src/api/axios.ts
  src/components/Profile.tsx
  src/components/ProfileContainer.tsx
  src/components/SubTitle.tsx
  src/pages/Home.tsx
Labels: 👩‍💻 Feat

#218 feat: 채팅 내역 저장하기 구현
  src/components/header/SubHeader.tsx
  src/pages/Chat.tsx
Labels: 👩‍💻 Feat

#225 fix: cicd.yml -> 환경변수 생성하는 로직 추가
  .github/workflows/cicd.yml
Labels: 🐞 Bug

#227 chore: DEVELOP -> DEVELOPE 오타 수정
  src/components/button/KakaoLoginButton.tsx
Labels: ⚙️ Chore

#229 feat: 홈페이지 -> "로그인이 필요합니다" 모달
  src/components/StrokeBanner.tsx
  src/components/SubTitle.tsx
  src/components/modal/ActionConfirmModal.tsx
Labels: 👩‍💻 Feat

#219 feat : GA4 trackedpage 추가 및 click 이벤트 할당 (정준영 part)
  src/App.tsx
  src/components/Profile.tsx
  src/components/SubTitle.tsx
  src/components/button/ChatStartButton.tsx
  src/components/button/KakaoLoginButton.tsx
  src/components/button/LoginButton.tsx
  src/components/button/RestartButton.tsx
  src/components/button/ShareButton.tsx
  src/components/header/MainHeader.tsx
  src/components/tips/TipsMenu.tsx
  src/pages/MbtiTestIntro.tsx
  src/pages/MbtiTestQuestions.tsx
  src/pages/MbtiTestResult.tsx
  src/utils/trackClickEvent.ts
Labels: 👩‍💻 Feat

#232 Feat/친구 채팅 제목에 이름 띄우기
  src/App.tsx
  src/components/Profile.tsx
  src/pages/Chat.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#235 feat: 로그인 시에만 my info 접근 가능하도록 조건 추가
  src/pages/MyInfo.tsx
Labels: 👩‍💻 Feat

#236 fix: select info 화면 내 공유하기 버튼 제거
  src/pages/SelectInfo.tsx
Labels: 🐞 Bug

#237 feat: 친구 채팅 history 구현
  src/pages/Chat.tsx
Labels: 👩‍💻 Feat

#239 feat: 일반 콘텐츠 header 문구 변경
  src/pages/Content.tsx
Labels: 👩‍💻 Feat

#241 fix: 친구 저장하기 버튼 문구, navigate 수정 및 ga element 변경
  src/pages/SelectInfo.tsx
Labels: 🐞 Bug, 🛠️ Fix

#247 fix: 일반 콘텐츠의 navigate 수정
  src/pages/Content.tsx
Labels: 🐞 Bug
