Repository MBTips/FE-MBTips, pull requests merged in 2025-05, with the labels that each got.

#243 feat: twitter svg 디자인 시안으로 변경, alert -> Toast로 대체
  public/icon/twitter.svg
  src/components/button/TwitterShareButton.tsx
  src/components/button/UrlCopyButton.tsx
Labels: 👩‍💻 Feat

#242 Feature/채팅 컨텐츠 페이지 개발
  src/App.tsx
  src/api/axios.ts
  src/components/tips/TipsMenu.tsx
  src/components/tips/TipsMenuContainer.tsx
  src/index.css
  src/mock/chatRecommend.ts
  src/mock/tips.ts
  src/pages/Chat.tsx
  src/pages/ChatRecommend.tsx
  src/pages/ChatTemperature.tsx
  src/pages/ChatTemporature.tsx
  src/pages/ChatTips.tsx
  vite.config.ts
Labels: 👩‍💻 Feat

#250 feat: 빠른 채팅 이름 띄우기
  src/pages/Chat.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#251 feat: 사용자 로그인 유지 기한 관리
  src/App.tsx
  src/store/useAuthStore.ts
Labels: 👩‍💻 Feat

#256 fix : App.tsx checkSession 호출 이전 조건문에 parsedAuth 추가
  src/App.tsx
Labels: 🐞 Bug, 🛠️ Fix

#263 fix: Mbti test result 페이지에서 공유하기했을 때 url에 mbti가 들어갈 수 있도록 변경
  src/App.tsx
  src/pages/MbtiTestResult.tsx
  src/store/useMbtiTestState.ts
Labels: 🐞 Bug, 🛠️ Fix

#264 feature/페이지별 meta 데이터 삽입
  index.html
  package-lock.json
  package.json
  public/image/og_image.png
  src/App.tsx
  src/pages/Chat.tsx
  src/pages/ChatRecommend.tsx
  src/pages/ChatTemperature.tsx
  src/pages/ChatTips.tsx
  src/pages/Content.tsx
  src/pages/Home.tsx
  src/pages/Login.tsx
  src/pages/MbtiTestIntro.tsx
  src/pages/MbtiTestQuestions.tsx
  src/pages/MbtiTestResult.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#270 fix: useParams import문 제거
  src/pages/MbtiTestResult.tsx
Labels: 🐞 Bug, 🛠️ Fix

#266 bug: 특정 기기에서 가로 여백이 생기는 문제 해결
  src/components/header/Header.tsx
  src/components/modal/TermsAndPrivacyModal.tsx
  src/index.css
  src/pages/Chat.tsx
  src/pages/Content.tsx
  src/pages/Home.tsx
  src/pages/MbtiTestQuestions.tsx
  src/pages/MbtiTestResult.tsx
  src/pages/MyInfo.tsx
  src/pages/SelectInfo.tsx
Labels: 🐞 Bug, 🛠️ Fix

#273 chore: og:image content 값 수정
  src/App.tsx
Labels: ⚙️ Chore

#278 fix: img src가 "/public"으로 시작하는 코드 모두 삭제
  src/components/Profile.tsx
  src/components/header/MainHeader.tsx
  src/components/header/SubHeader.tsx
Labels: 🛠️ Fix
