Repository MBTips/FE-MBTips, pull requests merged in 2025-03, with the labels that each got.

#54 chore: index.css에 breakpoint 추가
  src/components/button/ChatStartButton.tsx
  src/index.css
Labels: 🎨 Style

#60 feat: select info 페이지 개발 작업
  public/icon/arrow_left.svg
  src/components/Header.tsx
  src/components/button/FormButton.tsx
  src/index.css
  src/pages/Home.tsx
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#64 fix: 컨텐츠 배너 종류, 순서, 사이즈 변경
  public/image/home_banner1_lg.png
  public/image/home_banner1_md.png
  public/image/home_banner1_sm.png
  public/image/home_banner2_lg.png
  public/image/home_banner2_md.png
  public/image/home_banner2_sm.png
  public/image/home_banner3_lg.png
  public/image/home_banner3_md.png
  public/image/home_banner3_sm.png
  public/image/home_banner_1.png
  public/image/home_banner_2.png
  public/image/home_banner_3.png
  public/image/home_banner_lg_3.png
  src/App.tsx
  src/components/Banner.tsx
  src/pages/Content.tsx
Labels: ⚙️ Chore

#66 feat: 화면 가운데 배치 작업
  src/App.tsx
  src/components/CenteredLayout.tsx
Labels: 👩‍💻 Feat

#69 feat: select info api 연동
  .gitignore
  package-lock.json
  src/pages/SelectInfo.tsx
  src/utils/helpers.ts
Labels: 👩‍💻 Feat

#80 feat: navigate to select info of virtual friend
  src/App.tsx
  src/components/StrokeBanner.tsx
  src/components/SubTitle.tsx
  tsconfig.app.json
  vite.config.ts
Labels: 👩‍💻 Feat

#82 fix: 30대 이상 버튼 수정
  src/utils/helpers.ts
Labels: 🐞 Bug

#84 1차 배포 Test (Dev -> Main)
  public/icon/restart.svg
  public/image/ENTP.png
  public/image/Rectangle.png
  public/image/mbti_test.png
  public/image/mbti_test_result_image.png
  src/App.tsx
  src/components/StrokeBanner.tsx
  src/components/SubTitle.tsx
  src/components/button/MbtiAnswerButtons.tsx
  src/components/button/RestartButton.tsx
  src/components/button/ShareButton.tsx
  src/constants/MBTI_RESULT_INFO.ts
  src/constants/TEST_QNA.ts
  src/index.css
  src/pages/MbtiTestIntro.tsx
  src/pages/MbtiTestQuestions.tsx
  src/pages/MbtiTestResult.tsx
  src/utils/helpers.ts
  tsconfig.app.json
  vite.config.ts
Labels: 👩‍💻 Feat

#86 fix: 전체 레이아웃 내 background color 적용
  src/App.tsx
  src/components/CenteredLayout.tsx
Labels: 🎨 Style

#92 feat: 배포환경 및 로컬환경 https 처리 구분 및 스크립트 수정
  package.json
  vite.config.ts
Labels: 👩‍💻 Feat

#90 fix: header component border css
  src/components/Header.tsx
Labels: 🎨 Style

#94 fix: select info 제목이 mode에 따라 달라지도록 수정
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#100 3차 배포 Test (Dev -> Main)
  .github/workflows/ci.yml
  Dockerfile
  package.json
  src/components/Indicator.tsx
  vite.config.ts
Labels: 👩‍💻 Feat

#102 fix: fast friend api 전달 시 interests값 추가
  src/pages/SelectInfo.tsx
Labels: 👩‍💻 Feat

#103 feat: content api 연동 작업
  src/pages/Content.tsx
Labels: 👩‍💻 Feat

#105 feat: 파일이 존재할 때만 fs.readFileSync를 실행하도록 설정
  vite.config.ts
Labels: 👩‍💻 Feat
